project:
  type: website
  output-dir: "."

website:
  title: "RHOzon CV"
  navbar:
    left:
      - href: CV_testA.qmd
        text: CV

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

